config/routes.rb
ClarkTravel::Application.routes.draw do
  # resources :customers

  resource :session, only: [:create, :destroy, :new]
  resources :users do
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
  end
  resources :promotions, :testimonials
  resources :booking_categories do
    resources :bookings
  end
  
  resources :bookings
  
  resources :password_resets, only: [:new, :edit, :update, :create]
  resources :german_cruising_forms, only: [:new, :create, :edit]
  
  resources :downloads, only: [:index]
  
  root to: "promotions#index"
  
  
  
  post "users/:id/contact_me", to: "users#send_contact_me_email", as: "user_contact_me"
  post "users/sort", to: "users#sort", as: "sort_users"
  post "promotions/sort", to: "promotions#sort", as: "sort_promotions"
  post "testimonials/sort", to: "testimonials#sort", as: "sort_testimonials"
  
  get 'session', to: redirect('/')
  get 'auth/:provider/callback', to: 'users#update_facebook_auth', as: "facebook_callback"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
end

app/models/booking_category.rb
# == Schema Information
#
# Table name: booking_categories
#
#  id                   :integer          not null, primary key
#  title                :string(255)      not null
#  position             :integer
#  description          :text
#  created_at           :datetime
#  updated_at           :datetime
#  user_id              :integer          not null
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  display              :boolean          default(TRUE), not null
#

class BookingCategory < ActiveRecord::Base
  validates :title, :user, presence: true
  
  has_attached_file :picture,
                    :styles => { :small => "160x86", :medium => "700x332>", :large => "748x348", :thumb => "100x100>" },
                    :default_url => ":style/resources_air_delays.gif",
                    :bucket => ENV["AWS_BUCKET"]
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  
  
  has_many(
    :bookings,
    class_name: "Booking",
    foreign_key: :category_id,
    primary_key: :id,
    inverse_of: :category
  )
  
  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :booking_categories
  )
  
  def self.all_active
    self.order(:position).all
  end
  
end

app/controllers/booking_categories_controller.rb
# == Schema Information
#
# Table name: booking_categories
#
#  id                   :integer          not null, primary key
#  title                :string(255)      not null
#  position             :integer
#  description          :text
#  created_at           :datetime
#  updated_at           :datetime
#  user_id              :integer          not null
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  display              :boolean          default(TRUE), not null
#

class BookingCategoriesController < ApplicationController
    before_action :require_signed_in!, only: [:new, :create, :edit, :update, :destroy, :sort]
    before_action :set_booking_category, only: [:show, :edit, :update, :destroy]
  
    def index
      @active_booking_categories = BookingCategory.all_active
      
      
    end

    def new
      @booking_category = current_user.booking_categories.new
    end

    def create
      @booking_category = current_user.booking_categories.build(permitted_params.booking_category)

      if @booking_category.save
        flash.now[:notices] = ["Booking Category: #{@booking_category.title} created!"]
        render :edit
      else
        flash.now[:errors] = @booking_category.errors.full_messages
        render :new
      end
    end

    def show
      @category_bookings = @booking_category.bookings.order(:position)
    end

    def edit

    end

    def update
      if @booking_category.update_attributes(permitted_params.booking_category)
        flash.now[:notices] = ["Promotion Updated."]
      else
        flash.now[:errors] = @booking_category.errors.full_messages
      end
    
      render :edit
    end

    def destroy
      @booking_category.destroy
      flash[:notice] = ["Category \"#{@booking_category.title}\" deleted!"]
      redirect_to :index
    end
  
    def sort
      params[:booking_category].each_with_index do |id, index|
        BookingCategory.update_all({position: index+1}, {id: id})
      end
    
      render nothing: true
    end
  
    private
  
 
    def set_booking_category
      @booking_category = BookingCategory.find(params[:id])
    end
  
end

app/helpers/booking_categories_helper.rb
# == Schema Information
#
# Table name: booking_categories
#
#  id                   :integer          not null, primary key
#  title                :string(255)      not null
#  position             :integer
#  description          :text
#  created_at           :datetime
#  updated_at           :datetime
#  user_id              :integer          not null
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  display              :boolean          default(TRUE), not null
#

module BookingCategoriesHelper
end

app/views/booking_categories/_form.html.erb
<%= simple_form_for @booking_category, html: {class: "form", multipart: true} do |f| %>
  <div class="form">
    <div class="col-xs-12">

    	<h1><%= @booking_category.form_header_text + " #{@booking_category.title}" %></h1>
    	<p><%= image_tag @booking_category.picture.url(:small), class: "photo" %></p>
    
      <div class="input">
        <label for="avatar">JPEG Photo (Minimum 360x450):</label>
        <input id="avatar" type="file" name="booking_category[picture]" value="">
      </div>
  
 	
    </div>
  
    <div class="col-xs-12 text-center">
  
      
        <%= f.input :title, html: { class: "form-group" }, input_html: { class: "form-control" } %>

  

        <%= f.input :description, html: { class: "form-group" }, input_html: { class: "form-control" } %>

    
        <div class="form-actions form-group submit">
          <%= f.submit @booking_category.button_text %>
        </div>

    </div>
  </div>
<% end %>

app/views/booking_categories/_show.html.erb
<figure class="figure">
  <%= image_tag(booking_category.picture.url(:small), class: "image", alt: booking_category.title) %>
  <figcaption class="">
    <h1>
      <%= link_to booking_category.title, booking_category_url(booking_category), class: "h1-a category-link" %>
      <%= link_to edit_booking_category_url(booking_category) do  image_tag("edit-icon-32.png", class: "edit-icon") end if current_user_is_admin? %>
    </h1>
   
    
    <ul class="list-group">
      <% category_bookings.order(:position).each do |booking| %>
    		<li class="list-group-item blurb">
        	<%= link_to booking.title, booking.url %> <%= link_to edit_booking_url(booking), class: "edit-link" do %>
          <i class="fa fa-pencil-square-o"></i>
          <% end if current_user_is_admin? %>
        </li>
      <% end %>
  		<li class="list-group-item blurb">
      	<%= link_to new_booking_category_booking_path(booking_category), class: "edit-link" do %>
          <i class="fa fa-plus-circle"></i>
        <% end if current_user_is_admin? %>
      </li>
    </ul>
  </figcaption>
</figure>
 

app/views/booking_categories/edit.html.erb
<%= render "form", booking_category: @booking_category %>

app/views/booking_categories/index.html.erb
<% @active_booking_categories.each do |category| %>
  <div class="col-xs-12 col-sm-6 col-md-4 category row-padding booking-categories">
    <div class="category-container">
      <%= render "show", booking_category: category, category_bookings: category.bookings %>
    </div>
  </div>
<% end %>

app/views/booking_categories/new.html.erb
<%= render "form", booking_category: @booking_category %>

app/views/booking_categories/show.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 category row-padding">
  <div class="category-container">
    <%= render "show", booking_category: @booking_category, category_bookings: @category_bookings %>
  </div>
</div>