config/routes.rb
ClarkTravel::Application.routes.draw do
  # resources :customers

  resource :session, only: [:create, :destroy, :new]
  resources :users do
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
  end
  resources :promotions, :testimonials
  resources :booking_categories do
    resources :bookings
  end
  
  resources :bookings
  
  resources :password_resets, only: [:new, :edit, :update, :create]
  resources :german_cruising_forms, only: [:new, :create, :edit]
  
  resources :downloads, only: [:index]
  
  root to: "promotions#index"
  
  
  
  post "users/:id/contact_me", to: "users#send_contact_me_email", as: "user_contact_me"
  post "users/sort", to: "users#sort", as: "sort_users"
  post "promotions/sort", to: "promotions#sort", as: "sort_promotions"
  post "testimonials/sort", to: "testimonials#sort", as: "sort_testimonials"
  
  get 'session', to: redirect('/')
  get 'auth/:provider/callback', to: 'users#update_facebook_auth', as: "facebook_callback"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
end

app/models/promotion.rb
# == Schema Information
#
# Table name: promotions
#
#  id                    :integer          not null, primary key
#  title                 :string(255)      not null
#  user_id               :integer          not null
#  highlight             :text
#  body                  :text
#  start_date            :date
#  expiration_date       :date
#  created_at            :datetime
#  updated_at            :datetime
#  picture_file_name     :string(255)
#  picture_content_type  :string(255)
#  picture_file_size     :integer
#  picture_updated_at    :datetime
#  position              :integer          default(0), not null
#  display               :boolean          default(TRUE), not null
#  facebook_publish      :boolean          default(FALSE), not null
#  carousel_display      :boolean          default(FALSE), not null
#  facebook_published_at :datetime
#  facebook_id           :string(255)
#

class Promotion < ActiveRecord::Base
  # validates :expiration_date, presence: true, date: { after: lambda { |e| e.start_date}, message: "Must proceed the start date." }
  validates :title, :user, :start_date, presence: true
  # validates :facebook_publish, inclusion: { in: [true, false] }
  
  has_attached_file :picture,
                    :styles => { :small => "160x86", :medium => "700x332>", :large => "748x348", :thumb => "100x100>" },
                    :default_url => ":style/promotion_missing.png",
                    :bucket => ENV["AWS_BUCKET"]
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  
  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :promotions
  )
  
  delegate :facebook, to: :user
  
  # can refactor this to work with all models
  def model_path
    Rails.application.routes.url_helpers.promotion_path(self)
  end
  
  def model_url(host = "http://www.clark-travel.com")
    Rails.application.routes.url_helpers.promotion_url(self, host: host)
  end

  def description_tag_str
    if (self.body && !self.body.blank?)
      self.body
    elsif (self.highlight && !self.highlight.blank?)
      self.highlight
    else
      self.title
    end
  end
  
  def facebook_options(host = "http://www.clark-travel.com")
    @options ||= (start_date.past? || start_date.today?) ? {
      name: title,
      # message: body,
      # caption: highlight,
      # description: body,
      link: model_url,
      # picture: picture.url(:thumb)
    } : {
      name: title,
      # caption: highlight,
      # message: body,
      # description: body,
      link: model_url,
      # picture: picture.url(:thumb),
      scheduled_publish_time: start_date.to_time.to_i,
      published: false
    }
    
    # scheduled_publish_time must be in UNIX timestamp (aka # seconds since 1970 GMT)
  end
  
  def publish_to_facebook!(skip_check = false)
    if (skip_check || publish_to_facebook?)
      # TODO (08-08-2017): Potential error if Oauth token expires.
      self.facebook_id = Koala::Facebook::API.new(user.facebook.get_page_access_token("clarktravelagency")).put_connections("clarktravelagency", "feed", facebook_options)["id"]
      # self.facebook_id = Koala::Facebook::API.new(user.facebook.get_page_access_token("clarktravelagency")).put_object("clarktravelagency", "feed", facebook_options)["id"]
      self.facebook_published_at = DateTime.now
      self.save!
    else
      false
    end
  end  
  
  def publish_to_facebook?
    # TODO (08-08-2017): REMOVE / add: (only publish once)|| (facebook_published_at < updated_at)
    facebook_publish && facebook_published_at.nil?
  end
  
  def self.all_active
    self.where("current_date between start_date and expiration_date").order(:position).all
  end
  
  def self.all_active_carousel
    self.where(carousel_display: true).where("current_date between start_date and expiration_date").order(:position).all
  end
  
  def overdue_by_str
    return "never expires" if self.expiration_date.nil?
    "#{self.overdue_by} #{@overdue_str} #{@overdue_or_left}"
  end

  # returns the lowest denomination of how much it's overdue
  def overdue_by
    @overdue_str = "minutes"
    @overdue_or_left = "expired"
    
    return "never expires" if self.expiration_date.nil?
    overdue = (Time.zone.now - self.expiration_date.to_datetime)
    
    if (overdue < 0)
      overdue *= -1
      @overdue_or_left = "left"
    end
    
    overdue /= 60
    
    if overdue > 60
      overdue /=  60
      @overdue_str = "hours"
      if overdue > 24
        overdue /= 24
        @overdue_str = "days"
        if overdue > 7
          overdue /= 7
          @overdue_str = "weeks"
          if overdue > 4
            overdue /= 4
            @overdue_str = "months"
            if overdue > 12
              overdue /= 12
              @overdue_str = "yrs"
            end
          end
        end
      end
    end
    
    @overdue_str = @overdue_str[0..-2] if overdue == 1
    
    overdue.round
  end
end

app/controllers/promotions_controller.rb
# == Schema Information
#
# Table name: promotions
#
#  id                    :integer          not null, primary key
#  title                 :string(255)      not null
#  user_id               :integer          not null
#  highlight             :text
#  body                  :text
#  start_date            :date
#  expiration_date       :date
#  created_at            :datetime
#  updated_at            :datetime
#  picture_file_name     :string(255)
#  picture_content_type  :string(255)
#  picture_file_size     :integer
#  picture_updated_at    :datetime
#  position              :integer          default(0), not null
#  display               :boolean          default(TRUE), not null
#  facebook_publish      :boolean          default(FALSE), not null
#  carousel_display      :boolean          default(FALSE), not null
#  facebook_published_at :datetime
#  facebook_id           :string(255)
#

class PromotionsController < ApplicationController
  before_action :require_signed_in!, only: [:new, :create, :edit, :update, :destroy, :sort]
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found 
  # after_action :push_to_facebook, only: [:create, :update]
  
  # Root URL
  def index
    @active_promotions = Promotion.all_active
    (@all_promotions = Promotion.order(:expiration_date).all) if current_user_is_admin?
    @carousel_bookings = Booking.carousel_bookings
  end

  def new
    @promotion = current_user.promotions.new
  end

  def create
    @promotion = current_user.promotions.build(permitted_params.promotion)

    if @promotion.save
      push_to_facebook
      flash.now[:notices] = ["Promotion created!"]
      render :edit
    else
      flash.now[:errors] = @promotion.errors.full_messages
      render :new
    end
    
  end

  def show
  end

  def edit

  end

  def update
    if @promotion.update_attributes(permitted_params.promotion)
      flash.now[:notices] = ["Promotion Updated."]
      push_to_facebook
    else
      flash.now[:errors] = @promotion.errors.full_messages
    end
    
    render :edit
  end

  def destroy
    @promotion.destroy
    flash[:notice] = ["Promotion \"#{@promotion.title}\" deleted!"]

    respond_to do |format|
      format.html { redirect_to :root }
      format.js { render :nothing, status: :deleted }
    end
  end
  
  def sort
    params[:promotion].each_with_index do |id, index|
      Promotion.update_all({position: index+1}, {id: id})
    end
    
    render nothing: true
  end
  
  private
  
  def push_to_facebook
    @promotion.publish_to_facebook!
  end
 
  #TODO: refactor to a helper method that all controllers can use for their models
  def set_promotion
    @promotion = Promotion.find(params[:id])
  end
  
  # Refactor to a helper
  def record_not_found
    flash[:errors] = ["Record not found."]
    redirect_to promotions_path
  end

end

app/helpers/promotions_helper.rb
# == Schema Information
#
# Table name: promotions
#
#  id                    :integer          not null, primary key
#  title                 :string(255)      not null
#  user_id               :integer          not null
#  highlight             :text
#  body                  :text
#  start_date            :date
#  expiration_date       :date
#  created_at            :datetime
#  updated_at            :datetime
#  picture_file_name     :string(255)
#  picture_content_type  :string(255)
#  picture_file_size     :integer
#  picture_updated_at    :datetime
#  position              :integer          default(0), not null
#  display               :boolean          default(TRUE), not null
#  facebook_publish      :boolean          default(FALSE), not null
#  carousel_display      :boolean          default(FALSE), not null
#  facebook_published_at :datetime
#  facebook_id           :string(255)
#

module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= simple_form_for @promotion, html: {class: "form", multipart: true} do |f| %>
  <div class="form">
    <div class="col-xs-12">
    	<%= auth_token %>
    
      <% if promotion.persisted? %>
        <input type="hidden" name="_method" value="put"/>
      
        <%= link_to "&#10006".html_safe, promotion_url(promotion), method: :delete, confirm: "Really delete Promotion \"#{promotion.title}\"?", class: "right delete-button" if current_user_is_admin? %>
      <% end %>
      <%= link_to "back", request.referrer, class: "right" %>
    
    	<div class="page-header text-center">
        <h1><%= (promotion.persisted?) ? "Edit" : "New" %> Promotion <%= "\"#{promotion.title}\"" if promotion.persisted? %></h1>
      </div>
      
    	<p><%= image_tag promotion.picture.url(:medium), class: "photo" %></p>
    
      <div class="input form-group">
        <label for="photo">JPEG Photo (Maximum 760x360):</label>
        <input class="form-control" id="photo" type="file" name="promotion[picture]" value="<%= promotion.picture.url(:large) if promotion.persisted? %>">
      </div>
    </div>
  
    <div class="col-xs-12 col-sm-6 text-center">  
    	<h2>Promotion Content</h2>
      
    	<%= f.input :title, html: { class: "form-group" }, input_html: { class: "form-control" } %>
    
      <div class="input">
        <label for="highlight">Highlight</label>
    		<textarea id="highlight" type="text" name="promotion[highlight]"><%= promotion.highlight if promotion.present? %></textarea>
      </div>
    </div>
    
    <div class="col-xs-12 col-sm-6 text-center promotion-body"> 
      <div class="input form-group">
        <label for="body">Body</label>
    		<textarea class="form-control" id="body" type="text" rows="10" cols="88" name="promotion[body]"><%= promotion.body if promotion.present? %></textarea>
      </div>
    </div>
    
    <div class="col-xs-12 col-sm-6 text-center"> 
    	<h1>Promotion Timeline</h1>
    
      <div class="input">
        <label for="start-date">Start:</label>
        <input id="start-date" type="date" name="promotion[start_date]" value="<%= promotion.start_date || Date.today %>">
      </div>
    
      <div class="input">
        <label for="expiration-date">Expiration:</label>
        <input id="expiration-date" type="date" name="promotion[expiration_date]" value="<%= promotion.expiration_date || Date.today.advance(years: 1) %>">
      </div>
    </div>
    
    <div class="col-xs-12 col-sm-6 text-center"> 
   	  <h1>Display:</h1>

      <div class="checkbox-group">
     
        <div class="checkbox-input" id="display">
          <h4 for="display">Display in '<%= link_to "Home Page", root_url %>' Promotions Listing:</h4>
       
          <label for="display_on" class="left">Display on:</label>
           <input class="left" type="radio" name="promotion[display]" id="display_on" <%= "checked" if promotion.display %> value="<%= true %>">
       
           <label for="display_off" class="left">Display off:</label>
           <input class="left" type="radio" name="promotion[display]" id="display_off" <%= "checked" unless promotion.display %> value="<%= false %>">
        </div>
     
        <div class="checkbox-input" id="carousel_display">
          <h4 for="carousel_display">Display in '<%= link_to "Home Page", root_url %>' carousel:</h4>
       
          <label for="carousel_display_on" class="left">Display on:</label>
          <input class="left" type="radio" name="promotion[carousel_display]" id="carousel_display_on" <%= "checked" if promotion.persisted? && promotion.carousel_display %> value="<%= true %>">
       
          <label for="carousel_display_off" class="left">Display off:</label>
          <input class="left" type="radio" name="promotion[carousel_display]" id="carousel_display_off" <%= "checked" unless !promotion.persisted? && promotion.carousel_display %> value="<%= false %>">
        </div>
      </div>
     
      <div class="checkbox-group">
        <h4>Publish to Social Media:</h4>
        <div class="checkbox-input">
          <label for="facebook-publish">Facebook:</label>
          <input type="checkbox" name="promotion[facebook_publish]" id="facebook-publish" <%= "checked" if promotion.facebook_publish %> value="<%= true %>">
        </div>
        <div class="checkbox-input">
        </div>
    </div>
    
    <div class=" form-group submit">
      <%= f.submit @promotion.button_text %>
    </div>
  </div>
<% end %>
  

app/views/promotions/_index.html.erb
<div class="table-responsive promotions-table">
     <table class="table table-condensed table-hover">
		<tbody>
      <tr>
  			<th>Title</th>
  			<th>Photo</th>
  			<th>Start</th>
  			<th>Expire</th>
  			<th>Days Remaining</th>
  			<th>Edit</th>
  			<th>Delete</th>
		  </tr>
	
      <% promotions.each do |promotion| %>
    		<tr>
        	<td><strong><%= link_to promotion.title, promotion_url(promotion) %></strong></td>
    			<td>
            <a href="<%= edit_promotion_url(promotion) %>" onclick="this.target='_blank'"><%= image_tag promotion.picture.url(:small), class: "photo" %></a>
    			</td>
          <td><%= promotion.start_date.strftime("%d/%m/%Y") %></td>
    			<td><%= (promotion.expiration_date.nil?) ? promotion.overdue_by_str : promotion.expiration_date.strftime("%d/%m/%Y") %></td>
    			<td><span style="color: #6599FF"><%= promotion.overdue_by_str %></span></td>
          <td><%= link_to edit_promotion_url(promotion) do  image_tag("edit-icon-32.png") end %></td>
    			<td><%= link_to "&#10006".html_safe, promotion_url(promotion), method: :delete, data: { confirm: "Really delete Promotion \"#{promotion.title}\"?" }, class: "right" if current_user_is_admin? %>
    		</tr>
      <% end %>
	  </tbody>
  </table>
</div>

app/views/promotions/edit.html.erb
<%= render "form", promotion: @promotion %>

app/views/promotions/index.html.erb
<div class="col-xs-12 row-padding">
  <div class="owl-carousel promotions-carousel">
    <% @active_promotions.select { |p| p.carousel_display }.each do |promotion| %>
      <div class="item">
        <a class="promotion-link" target="_blank" title="<%= promotion.highlight %>" href="<%= promotion_url(promotion) %>">
          <%= image_tag promotion.picture.url(:large), class: "photo" %>
          <span class="promotion-hovertext">
            <%= promotion.highlight %>
          </span>
        </a>
      </div>
    <% end %>
  </div>
</div>

<div class="col-xs-12 col-md-6 yourtrip">
  <figure class="figure">
    <div class="owl-carousel bookings-carousel" id="bookings-carousel">
      <% @carousel_bookings.each do |booking| %>
        <div class="item">
          <a class="hovertext-small" target="_blank" title="<%= booking.title %>" href="<%= booking.url %>">
            <%= image_tag booking.picture.url(:small), class: "photo" %>
          </a>
        </div>
      <% end if @carousel_bookings%>
    </div>

    <figcaption>
    	<h1>Just In!</h1>
    	<p>Be sure to check out these new offers.</p>
    	<p><a href="<%= user_url(User.where(last_name: "Ocasio", first_name: "Ulrike").first.id, inquiry: "yourtrip.co") %>">Learn More</a></p>
    </figcaption>
  </figure>
</div>

<% if current_user_is_admin? %>  
  <div class="col-xs-12 col-md-6 new-promotion-blurb">
    <h1><%= link_to "New Promotion", new_promotion_url %></h1>
   	<p>To create a new promotion, follow the link below. To manage expired
 		and current promotions, visit the table below.</p>
    <p><%= link_to "New Promotion", new_promotion_url %></p>
    </div>
<% end %>



<ul id="promotions" class="<%= "sortable" if current_user_is_admin? %>" data-update-url="<%= sort_promotions_url %>">
  <% @active_promotions.each do |promotion| %>
    <%= content_tag_for :li, promotion, class: "" do %>
      <div class="col-xs-12 promotion promotion-row background-image">

          <figure class="figure">
            <%= image_tag promotion.picture.url(:large), class: "promotion-image" %>
    
            <figcaption class="">
              <%= link_to "&#10006".html_safe, promotion_path(promotion), method: :delete, class: "delete-button promotion-delete", data: {remote: true, confirm: "Really delete Promotion #{promotion.title}?"} if current_user_is_admin? %>
            	<h1><%= link_to promotion.title, promotion_url(promotion) %></h1>
            	<p><%= simple_format promotion.highlight[0..500] %></p>
            	<p><%= link_to "Learn More", promotion_url(promotion) %></p>
            </figcaption>
          </figure>

      </div>
    <% end %>
  <% end %>
</ul>

<% if current_user_is_admin? %>
  <div class="col-xs-12">
    <%= render "index", promotions: @all_promotions %>
  </div>
<% end %>

app/views/promotions/new.html.erb
<%= render "form", promotion: @promotion %>

app/views/promotions/show.html.erb
<% content_for :head do %>
  <meta property="fb:app_id" content="<%= ENV["FACEBOOK_APP_ID"] %>" />
  <meta property="og:url" content="<%= promotion_url(@promotion) %>" />
  <meta property="og:title" content="<%= @promotion.title || @promotion.highlight %>" />
  <meta property="og:description" content="<%= @promotion.description_tag_str %>" />
  <meta property="og:image" content="<%= @promotion.picture.url(:medium) || @promotion.picture.url(:thumb) %>" />
  <meta property="og:image:width" content="261" />
  <meta property="og:image:height" content="348" />
  <meta property="og:type" content="article" />

<% end %>

<div class="col-xs-12 text-center">
  <% if current_user_is_admin? %>  
    <%= link_to "&#10006".html_safe, promotion_url(@promotion), method: :delete, confirm: "Really delete Promotion \"#{@promotion.title}\"?", class: "right delete-button" %>
    <%= link_to edit_promotion_url(@promotion), class: "right" do image_tag("edit-icon-32.png") end %>
  <% end %>
	<h1><%= @promotion.title %></h1>
  
	<p><%= image_tag @promotion.picture.url(:large), class: "photo" %></p>
</div>
<div class="col-xs-12 text-center">  
	<h1><%= @promotion.highlight if @promotion.present? %></h1>
  
	<p id="body"><%= simple_format @promotion.body if @promotion.present? %></p>
</div>
<div class="col-xs-12 text-center">
	<h3>Promotion Timeline</h3>
  
  <div class="">
    <label for="start-date">Start:
    <p id="start-date"><%= @promotion.start_date %></p></label>
  </div>
  
  <div class="">
    <label for="expiration-date">Expiration:</label>
    <p id="expiration-date"><%= @promotion.expiration_date %></p>
  </div>
</div>

<div class="col-xs-12 text-center">
  <h1 class="center"><%= link_to "Contact us to learn more!", user_url(@promotion.user, inquiry_id: @promotion.id), class: "center" %></h1>
</div>