config/routes.rb
ClarkTravel::Application.routes.draw do
  # resources :customers

  resource :session, only: [:create, :destroy, :new]
  resources :users do
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
  end
  resources :promotions, :testimonials
  resources :booking_categories do
    resources :bookings
  end
  
  resources :bookings
  
  resources :password_resets, only: [:new, :edit, :update, :create]
  resources :german_cruising_forms, only: [:new, :create, :edit]
  
  resources :downloads, only: [:index]
  
  root to: "promotions#index"
  
  
  
  post "users/:id/contact_me", to: "users#send_contact_me_email", as: "user_contact_me"
  post "users/sort", to: "users#sort", as: "sort_users"
  post "promotions/sort", to: "promotions#sort", as: "sort_promotions"
  post "testimonials/sort", to: "testimonials#sort", as: "sort_testimonials"
  
  get 'session', to: redirect('/')
  get 'auth/:provider/callback', to: 'users#update_facebook_auth', as: "facebook_callback"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
end

app/models/testimonial.rb
# == Schema Information
#
# Table name: testimonials
#
#  id         :integer          not null, primary key
#  highlight  :string(255)
#  body       :text
#  user_id    :integer          not null
#  signature  :string(255)      not null
#  display    :boolean          default(TRUE), not null
#  position   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Testimonial < ActiveRecord::Base
  
  validates :body, :user, presence: true
  
  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id,
    inverse_of: :testimonials
  )
  
  def self.all_display
    self.where(display: true)
  end
  
  def display?
    display
  end
  
  def body_truncated(options = {truncated: true})
    return body unless options[:truncated]
    
    truncated_body = body[0..300]
    (body.length > 300) ? truncated_body  + "..." : truncated_body
  end
end

app/controllers/testimonials_controller.rb
# == Schema Information
#
# Table name: testimonials
#
#  id         :integer          not null, primary key
#  highlight  :string(255)
#  body       :text
#  user_id    :integer          not null
#  signature  :string(255)      not null
#  display    :boolean          default(TRUE), not null
#  position   :integer
#  created_at :datetime
#  updated_at :datetime
#

class TestimonialsController < ApplicationController
  before_action :require_signed_in!, only: [:new, :create, :edit, :update, :destroy, :sort]
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]
  
  def index
    @testimonial = current_user.testimonials.new if current_user_is_admin?
  end

  def new
    @testimonial = current_user.testimonials.new
  end

  def create
    @testimonial = current_user.testimonials.build(permitted_params.testimonial)
    
    
    if @testimonial.save
      flash.now[:notices] = ["Testimonial created!"]
      @testimonial = current_user.testimonials.new if current_user_is_admin?
    else
      flash.now[:errors] = @testimonial.errors.full_messages
    end
    
    @testimonials = Testimonial.all_display
    render :index
  end

  def show

  end

  def edit

  end

  def update
    if @testimonial.update_attributes(permitted_params.testimonial)
      flash.now[:notices] = ["Testimonial Updated."]
    else
      flash.now[:errors] = @testimonial.errors.full_messages
    end
    
    render :edit
  end

  def destroy
    @testimonial.destroy
    flash[:notice] = ["Testimonial \"#{@testimonial.highlight}\" deleted!"]
    redirect_to testimonials_url
  end
  
  def sort
    params[:testimonial].each_with_index do |id, index|
      Testimonial.update_all({position: index+1}, {id: id})
    end
    
    render nothing: true
  end
  
  private
  
  def set_testimonial
    @testimonial = Testimonial.find(params[:id])
  end
end

app/helpers/testimonials_helper.rb
# == Schema Information
#
# Table name: testimonials
#
#  id         :integer          not null, primary key
#  highlight  :string(255)
#  body       :text
#  user_id    :integer          not null
#  signature  :string(255)      not null
#  display    :boolean          default(TRUE), not null
#  position   :integer
#  created_at :datetime
#  updated_at :datetime
#

module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<div class="contentFull">
    <form action="<%= testimonial.persisted? ? testimonial_url(testimonial) : testimonials_url %>" enctype="multipart/form-data" method="post">
  	<%= auth_token %>
    <% if testimonial.persisted? %>
      <input type="hidden" name="_method" value="put"/>
    
      <%= link_to "&#10006".html_safe, testimonial_url(testimonial), method: :delete, data: {confirm: "Really delete Testimonial \"#{testimonial.highlight}\"?"}, class: "right delete-button" if current_user_is_admin? %>
    <% end %>
    <%= link_to "back", request.referrer, class: "right" %>
    
  	<h1><%= testimonial.persisted? ? "Edit": "New" %> Testimonial</h1>
  
  	<div class="input">
      <label for="highlight">Highlight</label>
  		<input id="highlight" type="text" name="testimonial[highlight]" value="<%= testimonial.highlight %>">
    </div>
  
  	<div class="input long-input">
      <label for="body">Body</label>
  		<textarea id="body" name="testimonial[body]"><%= testimonial.body %></textarea>
    </div> 
  
  	<div class="input">
      <label for="signature">Signature</label>
  		<input id="signature" type="text" name="testimonial[signature]" value="<%= testimonial.signature %>">
    </div> 
	
    <div class="submit long-submit left">
      <input type="submit" value="<%= testimonial.persisted? ? "Update" : "Create" %>">
    </div>
  </form>
</div>

app/views/testimonials/_show.html.erb
<div class="col-xs-12 testimonial">
	<%= link_to "&#10006".html_safe, testimonial_url(testimonial), data: {confirm: "Really delete Testimonial \"#{testimonial.highlight}\"?" }, method: :delete, class: "delete-button" if current_user_is_admin? %>
<% current_test_url = (current_user_is_admin? ? edit_testimonial_url(testimonial) : testimonial_url(testimonial)) %>
	<h1><%= link_to("\"#{testimonial.highlight}\"", current_test_url) %></h1>
  
  <% @body = (@to_truncate) ? "\"#{testimonial.body_truncated}\"" : "\"#{testimonial.body}\"" %>
	<p><%= simple_format @body %></p>
  
	<h2 class="signature"><%= "-#{testimonial.signature}" unless testimonial.signature.blank? %></h2>
</div>

app/views/testimonials/edit.html.erb
<%= render "form", testimonial: @testimonial %>

app/views/testimonials/index.html.erb
<%= render "form", testimonial: @testimonial if current_user_is_admin? %>
<ul id="testimonials" class="<%= "sortable" if current_user_is_admin? %>" data-update-url="<%= sort_testimonials_url %>">
  <% @testimonials.each do |testimonial| %>
    <%= content_tag_for :li, testimonial, class: "testimonial" do %>
      <%= render "show", testimonial: testimonial %>
    <% end %>
  <% end %>
</ul>

app/views/testimonials/new.html.erb
<div class="contentFull">
  <%= render "form", testimonial: @testimonial if current_user_is_admin? %>
 <div class="contentFull">

app/views/testimonials/show.html.erb
<%= render "testimonials/show", testimonial: @testimonial %>    