config/routes.rb
ClarkTravel::Application.routes.draw do
  # resources :customers

  resource :session, only: [:create, :destroy, :new]
  resources :users do
    get :activate, on: :collection
    get :password_reset, on: :collection
    put :password_update, on: :collection
  end
  resources :promotions, :testimonials
  resources :booking_categories do
    resources :bookings
  end
  
  resources :bookings
  
  resources :password_resets, only: [:new, :edit, :update, :create]
  resources :german_cruising_forms, only: [:new, :create, :edit]
  
  resources :downloads, only: [:index]
  
  root to: "promotions#index"
  
  
  
  post "users/:id/contact_me", to: "users#send_contact_me_email", as: "user_contact_me"
  post "users/sort", to: "users#sort", as: "sort_users"
  post "promotions/sort", to: "promotions#sort", as: "sort_promotions"
  post "testimonials/sort", to: "testimonials#sort", as: "sort_testimonials"
  
  get 'session', to: redirect('/')
  get 'auth/:provider/callback', to: 'users#update_facebook_auth', as: "facebook_callback"
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="footer navbar">
    
  
      <% if @feed %>
        <div class="owl-carousel feed-carousel left">
          <% @feed.each do |post| %>
            <% next unless post["message"] %>
            <%= render "layouts/post", post: post %>    
          <% end %>
        </div>
      <% end %>
      
      
      <div class="owl-carousel no-imageFull testimonials-carousel">
        <% @testimonials.each do |testimonial| %>
          <div class="item">
            <%= render "testimonials/show", testimonial: testimonial, to_truncate: true %>    
          </div>
        <% end if @testimonials.present? %>
      </div>
      
      <div class="col-xs-12 col-sm-4">
        <a class="address" href="<%= page_path("directions") %>">
        	<ul>
        	  <li>(908) 595-0400</li>
          	<li>Fax (908) 595-0410</li>
          </ul>
        </a>
      </div>
      
      <div class="col-xs-12 col-sm-4">
        <a class="address" href="<%= page_path("directions") %>">
        	<ul>
            <li>3461 Route 22 East</li>
            <li>Branchburg NJ 08876</li>
          </ul>
        </a>
      </div>
      
      <div class="col-xs-12 col-sm-4 copyright">
      	<%= link_to "http://www.dougteixeira.com/", class: "ayos-logo" do %>
          <% image_tag("ayos_final_300x200.gif", width: 150, height: 100) %>
          <p><small>© Clark Travel Agency Inc. <%= Date.today.year %></small></p>
        <% end %>
      </div>
    


      <%  if Rails.env.development? %>
        <div class="col-xs-12 params group">
            <%= debug(params) %>
            <pre>This page was loaded on <strong><%=l Time.now, format: "%k:%M:%S:%L" %></strong></pre>
            <pre>return_url: <strong><%= session[:return_url] %></strong></pre>
            <pre>go_back: <strong><%= session[:go_back] %></strong></pre>
        </div>
      <% end %>

  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-inverse navbar-fixed-top" id="main-navigation" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        
        <button type="button" class="navbar-toggle toggle-x collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar" id="middle-bar"></span>
        </button>
        <%= link_to root_url, class: "navbar-brand", alt: "home" do %>
          <%= image_tag("clark_travel_logo.png", alt: "home") %>
        <% end %>
      </div>
    
      <div class="collapse navbar-collapse navbar-inverse" id="navbar-collapse-1">
        <ul class="navigation nav navbar-nav sticky-nav">
          <li class=""><a href="/">Home</a></li>
        	<li class=""><%= link_to "Disney", page_path("disney") %></li>
          <li class=""><a href="https://www.lomasagentportal.com/16452">Lomas Tours</a></li>
          <% "<li class=''><a href='#{page_path('german_cruising')}''>German-American Cruise</a></li>".html_safe %>
        	<li class=""><a href="<%= booking_categories_path %>">Book Online</a></li>
        	<li class=""><a href="<%= page_path("resources") %>">Resources</a></li>

        	

        </ul>
        
        <ul class="navigation nav navbar-nav nav-right sticky-nav">
        	<li class=""><a href="<%= page_path("about") %>">About</a></li>
        	<li class=""><a href="<%= users_url %>">Contact</a></li>
        	<li class=""><a href="<%= testimonials_url %>">Testimonials</a></li>
        	<li class=""><a href="<%= page_path("directions") %>">Directions</a></li>
          <% if signed_in? %>
          	<li class="dropdown">
              <%= link_to "#", class: "dropdown-toggle", id: "dropdownAgent", role: "button", data: { toggle: "dropdown"} do %>
                <%= "#{current_user.name }" %>
                <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownAgent">
                <li role="presentation"><%= link_to "Profile", edit_user_url(current_user), role: "menuitem", tabindex: "-1"  %></li>
                <li role="presentation"><%= link_to("Logout", session_url(), class: "logout",  method: :delete, role: "menuitem", tabindex: "-1" )%></li>
              </ul>
            </li>
           
                  
          <% else %>
            <li><%= link_to "Agent Login", new_session_url %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>   
</header>

app/views/layouts/_messages.html.erb
<div class="<%= class_name %> info">
  <%= messages_arr.join("<br>").html_safe unless (messages_arr.nil? || messages_arr.empty?) %>
</div>

app/views/layouts/_old_header.html.erb
<header class="header">
	<a class="logo hide-text" href="/">Clark Travel</a>
  <div class="group">
    <ul class="logins">
      <% if signed_in? %>
      
    	  <%= link_to edit_user_url(current_user) do %>
          <%= "#{current_user.name} " %><span class="caret"></span>
        <% end %>
        
        <ul class="dropdown-menu-1 hidden" aria-labelledby="">
          <li><%= link_to("Logout", session_url(), class: "logout",  method: :delete)%></li>
        </ul>
                      
      <% else %>
        <li><%= link_to "| Agent Login", new_session_url %></li>
        <li><%=  link_to "(908) 595-0400 || Directions | ", page_path("directions") %></li>
      <% end %>
  </div>
    
    
    <ul class="navigation">
    	<li class="nav-li"><a href="/">HOME</a></li>
    	<li class="nav-li"><a href="<%= testimonials_url %>">TESTIMONIALS</a></li>
    	<li class="nav-li"><a href="<%= page_path("resources") %>">RESOURCES</a></li>
    	<li class="nav-li"><a href="<%= page_path("disney") %>">DISNEY</a></li>
    	<li class="nav-li"><a href="<%= page_path("about") %>">ABOUT US</a></li>
    	<li class="nav-li"><a href="<%= page_path("german_cruising") %>">GERMAN CRUISES</a></li>
    	<li class="nav-li"><a href="<%= booking_categories_path %>">BOOK</a></li>
    	<li class="nav-li right"><a href="<%= users_url %>">Contact</a></li>
    </ul>
  </div>
</header>

app/views/layouts/_post.html.erb
<%= link_to (post["actions"] ? post["actions"].first["link"] : "https://facebook.com/clarktravelagency" ), class: "item post" do %>
  <div class="col-xs-8">
    <p class="left"><%= (post["message"].length > 400) ? post["message"][0..400] + "..." : post["message"]%></p>
  </div>
  
  <div class="col-xs-4">
    <%= image_tag post["picture"], class: "photo left" if post["picture"]%>
  </div>
  
  <div class="col-xs-12">
    <i class="fa fa-facebook-square fa-lg"></i>
    <small class="left">Posted on Facebook: <%= Time.parse(post["created_time"]).strftime("%b %d @ %I:%M")  %> </small>
   </div>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Clark Travel</title>
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico?v=2' %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= content_for?(:head) ? yield(:head) : '' %>
</head>
<body>


  <!-- Begin header. ********************************************************* -->
    <%= render "layouts/header" %>

  <!-- End header. *********************************************************** -->
  
  <!-- Begin Notification Area. *********************************************** -->
  
    <%= render "layouts/messages", messages_arr: flash[:notices], class_name: "notices" if flash[:notices] %>
    <%= render "layouts/messages", messages_arr: flash[:errors], class_name: "errors" if flash[:errors] %>
  
  <!-- End Notification Area. ************************************************* -->
  

  <!-- Begin standard content. *********************************************** -->
  <main class="container-fluid">
  
    <div class="row">
      <div class="main-content clearfix">
      	<%= yield %>
        <%= yield :js %>
      </div>
    </div>    
              
  </main>
  

  <!-- End standard content. ************************************************* -->

  <!-- Begin footer. ********************************************************* -->
    <%= render "layouts/footer" %>
  <!-- End footer. *********************************************************** -->

</body>
</html>

app/views/layouts/back_button.html.erb
<strong class="back-button dimmed"><%= link_to "<", request.referrer, title: "Back" %></strong>